# Generated by Django 6.0.4 on 2026-04-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_patient_address_appointment_ai_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.doctor'),
        ),
    ]
